import type { Metadata } from "next";
import { Fredoka } from "next/font/google";
import "./globals.css";
import Favicon from "/public/avatar.png";

const fredoka = Fredoka({ subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
  title: "Hannahs Portfolio",
  description: "Generated by create next app",
  icons: [{ url: Favicon.src, rel: "icon" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={fredoka.className}>{children}</body>
    </html>
  );
}
